export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const BEGIN_REGISTRATION_START = 'BEGIN_REGISTRATION_START';
export const BEGIN_REGISTRATION_SUCCESS = 'BEGIN_REGISTRATION_SUCCESS';
export const BEGIN_REGISTRATION_FAILURE = 'BEGIN_REGISTRATION_FAILURE';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const CREATE_ORGANIZATION_START = 'CREATE_ORGANIZATION_START';
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_FAILURE = 'CREATE_ORGANIZATION_FAILURE';

export const LOOKUP_ORGANIZATION_CODE_START = 'LOOKUP_ORGANIZATION_CODE_START';
export const LOOKUP_ORGANIZATION_CODE_SUCCESS = 'LOOKUP_ORGANIZATION_CODE_SUCCESS';
export const LOOKUP_ORGANIZATION_CODE_FAILURE = 'LOOKUP_ORGANIZATION_CODE_FAILURE';

export const GET_PROJECTS_START = 'GET_PROJECTS_START';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = ' GET_PROJECTS_FAILURE';

export const RESUME_SESSION_START = 'RESUME_SESSION_START';
export const RESUME_SESSION_SUCCESS = 'RESUME_SESSION_SUCCESS';
export const RESUME_SESSION_FAILURE = ' RESUME_SESSION_FAILURE';
